platform = ARGUMENTS.get('OS', Platform())

include_path = "#/src/"

import glob,os;
lib_path = []
for i in glob.glob("lib/*/lib"):
	lib_path.append("#"+i);


bin_path = ""
libs = ['json_linux-gcc-4.2.1_libmt']

env = Environment(PLATFORM = platform,
                  BINDIR = bin_path,
                  INCDIR = include_path,
                  LIBDIR = lib_path,
                  CPPPATH = [include_path],
                  LIBPATH = [lib_path],
                  LIBS = libs,
                  PROJ_BASE_DIR = "#")

Export('env')

env.SConscript('src/SConscript', variant_dir='build/$PLATFORM')

