// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#ifndef PROTOBUF_data_2eproto__INCLUDED
#define PROTOBUF_data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_data_2eproto();
void protobuf_AssignDesc_data_2eproto();
void protobuf_ShutdownFile_data_2eproto();

class Data;

// ===================================================================

class Data : public ::google::protobuf::Message {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Data& default_instance();

  void Swap(Data* other);

  // implements Message ----------------------------------------------

  Data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes i = 1;
  inline bool has_i() const;
  inline void clear_i();
  static const int kIFieldNumber = 1;
  inline const ::std::string& i() const;
  inline void set_i(const ::std::string& value);
  inline void set_i(const char* value);
  inline void set_i(const void* value, size_t size);
  inline ::std::string* mutable_i();
  inline ::std::string* release_i();
  inline void set_allocated_i(::std::string* i);

  // @@protoc_insertion_point(class_scope:Data)
 private:
  inline void set_has_i();
  inline void clear_has_i();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* i_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static Data* default_instance_;
};
// ===================================================================


// ===================================================================

// Data

// optional bytes i = 1;
inline bool Data::has_i() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Data::set_has_i() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Data::clear_has_i() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Data::clear_i() {
  if (i_ != &::google::protobuf::internal::kEmptyString) {
    i_->clear();
  }
  clear_has_i();
}
inline const ::std::string& Data::i() const {
  return *i_;
}
inline void Data::set_i(const ::std::string& value) {
  set_has_i();
  if (i_ == &::google::protobuf::internal::kEmptyString) {
    i_ = new ::std::string;
  }
  i_->assign(value);
}
inline void Data::set_i(const char* value) {
  set_has_i();
  if (i_ == &::google::protobuf::internal::kEmptyString) {
    i_ = new ::std::string;
  }
  i_->assign(value);
}
inline void Data::set_i(const void* value, size_t size) {
  set_has_i();
  if (i_ == &::google::protobuf::internal::kEmptyString) {
    i_ = new ::std::string;
  }
  i_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Data::mutable_i() {
  set_has_i();
  if (i_ == &::google::protobuf::internal::kEmptyString) {
    i_ = new ::std::string;
  }
  return i_;
}
inline ::std::string* Data::release_i() {
  clear_has_i();
  if (i_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = i_;
    i_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Data::set_allocated_i(::std::string* i) {
  if (i_ != &::google::protobuf::internal::kEmptyString) {
    delete i_;
  }
  if (i) {
    set_has_i();
    i_ = i;
  } else {
    clear_has_i();
    i_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_data_2eproto__INCLUDED
