// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeData.proto

package proto;

public final class EmployeeData {
  private EmployeeData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmployeeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 empId = 1;
    /**
     * <code>optional int64 empId = 1;</code>
     */
    boolean hasEmpId();
    /**
     * <code>optional int64 empId = 1;</code>
     */
    long getEmpId();

    // optional string empName = 2;
    /**
     * <code>optional string empName = 2;</code>
     */
    boolean hasEmpName();
    /**
     * <code>optional string empName = 2;</code>
     */
    java.lang.String getEmpName();
    /**
     * <code>optional string empName = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmpNameBytes();

    // repeated .Employee.PhoneNumber phoneNumber = 3;
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    java.util.List<proto.EmployeeData.Employee.PhoneNumber> 
        getPhoneNumberList();
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    proto.EmployeeData.Employee.PhoneNumber getPhoneNumber(int index);
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    int getPhoneNumberCount();
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    java.util.List<? extends proto.EmployeeData.Employee.PhoneNumberOrBuilder> 
        getPhoneNumberOrBuilderList();
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    proto.EmployeeData.Employee.PhoneNumberOrBuilder getPhoneNumberOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Employee(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Employee defaultInstance;
    public static Employee getDefaultInstance() {
      return defaultInstance;
    }

    public Employee getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              empId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              empName_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                phoneNumber_ = new java.util.ArrayList<proto.EmployeeData.Employee.PhoneNumber>();
                mutable_bitField0_ |= 0x00000004;
              }
              phoneNumber_.add(input.readMessage(proto.EmployeeData.Employee.PhoneNumber.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          phoneNumber_ = java.util.Collections.unmodifiableList(phoneNumber_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.EmployeeData.internal_static_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.EmployeeData.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.EmployeeData.Employee.class, proto.EmployeeData.Employee.Builder.class);
    }

    public static com.google.protobuf.Parser<Employee> PARSER =
        new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Employee.PHONETYPE}
     */
    public enum PHONETYPE
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>OFFICE = 2;</code>
       */
      OFFICE(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>OFFICE = 2;</code>
       */
      public static final int OFFICE_VALUE = 2;


      public final int getNumber() { return value; }

      public static PHONETYPE valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return OFFICE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PHONETYPE>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PHONETYPE>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PHONETYPE>() {
              public PHONETYPE findValueByNumber(int number) {
                return PHONETYPE.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.EmployeeData.Employee.getDescriptor().getEnumTypes().get(0);
      }

      private static final PHONETYPE[] VALUES = values();

      public static PHONETYPE valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PHONETYPE(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Employee.PHONETYPE)
    }

    public interface PhoneNumberOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional .Employee.PHONETYPE type = 1;
      /**
       * <code>optional .Employee.PHONETYPE type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>optional .Employee.PHONETYPE type = 1;</code>
       */
      proto.EmployeeData.Employee.PHONETYPE getType();

      // optional string number = 2;
      /**
       * <code>optional string number = 2;</code>
       */
      boolean hasNumber();
      /**
       * <code>optional string number = 2;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>optional string number = 2;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();
    }
    /**
     * Protobuf type {@code Employee.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage
        implements PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PhoneNumber(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                proto.EmployeeData.Employee.PHONETYPE value = proto.EmployeeData.Employee.PHONETYPE.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                number_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.EmployeeData.internal_static_Employee_PhoneNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.EmployeeData.internal_static_Employee_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.EmployeeData.Employee.PhoneNumber.class, proto.EmployeeData.Employee.PhoneNumber.Builder.class);
      }

      public static com.google.protobuf.Parser<PhoneNumber> PARSER =
          new com.google.protobuf.AbstractParser<PhoneNumber>() {
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional .Employee.PHONETYPE type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private proto.EmployeeData.Employee.PHONETYPE type_;
      /**
       * <code>optional .Employee.PHONETYPE type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Employee.PHONETYPE type = 1;</code>
       */
      public proto.EmployeeData.Employee.PHONETYPE getType() {
        return type_;
      }

      // optional string number = 2;
      public static final int NUMBER_FIELD_NUMBER = 2;
      private java.lang.Object number_;
      /**
       * <code>optional string number = 2;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string number = 2;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string number = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = proto.EmployeeData.Employee.PHONETYPE.MOBILE;
        number_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getNumberBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getNumberBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.EmployeeData.Employee.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(proto.EmployeeData.Employee.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Employee.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements proto.EmployeeData.Employee.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.EmployeeData.internal_static_Employee_PhoneNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.EmployeeData.internal_static_Employee_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.EmployeeData.Employee.PhoneNumber.class, proto.EmployeeData.Employee.PhoneNumber.Builder.class);
        }

        // Construct using proto.EmployeeData.Employee.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = proto.EmployeeData.Employee.PHONETYPE.MOBILE;
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.EmployeeData.internal_static_Employee_PhoneNumber_descriptor;
        }

        public proto.EmployeeData.Employee.PhoneNumber getDefaultInstanceForType() {
          return proto.EmployeeData.Employee.PhoneNumber.getDefaultInstance();
        }

        public proto.EmployeeData.Employee.PhoneNumber build() {
          proto.EmployeeData.Employee.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.EmployeeData.Employee.PhoneNumber buildPartial() {
          proto.EmployeeData.Employee.PhoneNumber result = new proto.EmployeeData.Employee.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.number_ = number_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.EmployeeData.Employee.PhoneNumber) {
            return mergeFrom((proto.EmployeeData.Employee.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.EmployeeData.Employee.PhoneNumber other) {
          if (other == proto.EmployeeData.Employee.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasNumber()) {
            bitField0_ |= 0x00000002;
            number_ = other.number_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.EmployeeData.Employee.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.EmployeeData.Employee.PhoneNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional .Employee.PHONETYPE type = 1;
        private proto.EmployeeData.Employee.PHONETYPE type_ = proto.EmployeeData.Employee.PHONETYPE.MOBILE;
        /**
         * <code>optional .Employee.PHONETYPE type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .Employee.PHONETYPE type = 1;</code>
         */
        public proto.EmployeeData.Employee.PHONETYPE getType() {
          return type_;
        }
        /**
         * <code>optional .Employee.PHONETYPE type = 1;</code>
         */
        public Builder setType(proto.EmployeeData.Employee.PHONETYPE value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Employee.PHONETYPE type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = proto.EmployeeData.Employee.PHONETYPE.MOBILE;
          onChanged();
          return this;
        }

        // optional string number = 2;
        private java.lang.Object number_ = "";
        /**
         * <code>optional string number = 2;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string number = 2;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string number = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string number = 2;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string number = 2;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000002);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional string number = 2;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          number_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Employee.PhoneNumber)
      }

      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Employee.PhoneNumber)
    }

    private int bitField0_;
    // optional int64 empId = 1;
    public static final int EMPID_FIELD_NUMBER = 1;
    private long empId_;
    /**
     * <code>optional int64 empId = 1;</code>
     */
    public boolean hasEmpId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 empId = 1;</code>
     */
    public long getEmpId() {
      return empId_;
    }

    // optional string empName = 2;
    public static final int EMPNAME_FIELD_NUMBER = 2;
    private java.lang.Object empName_;
    /**
     * <code>optional string empName = 2;</code>
     */
    public boolean hasEmpName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string empName = 2;</code>
     */
    public java.lang.String getEmpName() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          empName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string empName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmpNameBytes() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Employee.PhoneNumber phoneNumber = 3;
    public static final int PHONENUMBER_FIELD_NUMBER = 3;
    private java.util.List<proto.EmployeeData.Employee.PhoneNumber> phoneNumber_;
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    public java.util.List<proto.EmployeeData.Employee.PhoneNumber> getPhoneNumberList() {
      return phoneNumber_;
    }
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    public java.util.List<? extends proto.EmployeeData.Employee.PhoneNumberOrBuilder> 
        getPhoneNumberOrBuilderList() {
      return phoneNumber_;
    }
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    public int getPhoneNumberCount() {
      return phoneNumber_.size();
    }
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    public proto.EmployeeData.Employee.PhoneNumber getPhoneNumber(int index) {
      return phoneNumber_.get(index);
    }
    /**
     * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
     */
    public proto.EmployeeData.Employee.PhoneNumberOrBuilder getPhoneNumberOrBuilder(
        int index) {
      return phoneNumber_.get(index);
    }

    private void initFields() {
      empId_ = 0L;
      empName_ = "";
      phoneNumber_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, empId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmpNameBytes());
      }
      for (int i = 0; i < phoneNumber_.size(); i++) {
        output.writeMessage(3, phoneNumber_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, empId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmpNameBytes());
      }
      for (int i = 0; i < phoneNumber_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, phoneNumber_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.EmployeeData.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.EmployeeData.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.EmployeeData.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.EmployeeData.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.EmployeeData.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.EmployeeData.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.EmployeeData.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.EmployeeData.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.EmployeeData.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.EmployeeData.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.EmployeeData.Employee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.EmployeeData.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.EmployeeData.internal_static_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.EmployeeData.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.EmployeeData.Employee.class, proto.EmployeeData.Employee.Builder.class);
      }

      // Construct using proto.EmployeeData.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneNumberFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        empId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        empName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (phoneNumberBuilder_ == null) {
          phoneNumber_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          phoneNumberBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.EmployeeData.internal_static_Employee_descriptor;
      }

      public proto.EmployeeData.Employee getDefaultInstanceForType() {
        return proto.EmployeeData.Employee.getDefaultInstance();
      }

      public proto.EmployeeData.Employee build() {
        proto.EmployeeData.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.EmployeeData.Employee buildPartial() {
        proto.EmployeeData.Employee result = new proto.EmployeeData.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.empId_ = empId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.empName_ = empName_;
        if (phoneNumberBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            phoneNumber_ = java.util.Collections.unmodifiableList(phoneNumber_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.phoneNumber_ = phoneNumber_;
        } else {
          result.phoneNumber_ = phoneNumberBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.EmployeeData.Employee) {
          return mergeFrom((proto.EmployeeData.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.EmployeeData.Employee other) {
        if (other == proto.EmployeeData.Employee.getDefaultInstance()) return this;
        if (other.hasEmpId()) {
          setEmpId(other.getEmpId());
        }
        if (other.hasEmpName()) {
          bitField0_ |= 0x00000002;
          empName_ = other.empName_;
          onChanged();
        }
        if (phoneNumberBuilder_ == null) {
          if (!other.phoneNumber_.isEmpty()) {
            if (phoneNumber_.isEmpty()) {
              phoneNumber_ = other.phoneNumber_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePhoneNumberIsMutable();
              phoneNumber_.addAll(other.phoneNumber_);
            }
            onChanged();
          }
        } else {
          if (!other.phoneNumber_.isEmpty()) {
            if (phoneNumberBuilder_.isEmpty()) {
              phoneNumberBuilder_.dispose();
              phoneNumberBuilder_ = null;
              phoneNumber_ = other.phoneNumber_;
              bitField0_ = (bitField0_ & ~0x00000004);
              phoneNumberBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhoneNumberFieldBuilder() : null;
            } else {
              phoneNumberBuilder_.addAllMessages(other.phoneNumber_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.EmployeeData.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.EmployeeData.Employee) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 empId = 1;
      private long empId_ ;
      /**
       * <code>optional int64 empId = 1;</code>
       */
      public boolean hasEmpId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 empId = 1;</code>
       */
      public long getEmpId() {
        return empId_;
      }
      /**
       * <code>optional int64 empId = 1;</code>
       */
      public Builder setEmpId(long value) {
        bitField0_ |= 0x00000001;
        empId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 empId = 1;</code>
       */
      public Builder clearEmpId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        empId_ = 0L;
        onChanged();
        return this;
      }

      // optional string empName = 2;
      private java.lang.Object empName_ = "";
      /**
       * <code>optional string empName = 2;</code>
       */
      public boolean hasEmpName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string empName = 2;</code>
       */
      public java.lang.String getEmpName() {
        java.lang.Object ref = empName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          empName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string empName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmpNameBytes() {
        java.lang.Object ref = empName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string empName = 2;</code>
       */
      public Builder setEmpName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        empName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string empName = 2;</code>
       */
      public Builder clearEmpName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        empName_ = getDefaultInstance().getEmpName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string empName = 2;</code>
       */
      public Builder setEmpNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        empName_ = value;
        onChanged();
        return this;
      }

      // repeated .Employee.PhoneNumber phoneNumber = 3;
      private java.util.List<proto.EmployeeData.Employee.PhoneNumber> phoneNumber_ =
        java.util.Collections.emptyList();
      private void ensurePhoneNumberIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          phoneNumber_ = new java.util.ArrayList<proto.EmployeeData.Employee.PhoneNumber>(phoneNumber_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.EmployeeData.Employee.PhoneNumber, proto.EmployeeData.Employee.PhoneNumber.Builder, proto.EmployeeData.Employee.PhoneNumberOrBuilder> phoneNumberBuilder_;

      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public java.util.List<proto.EmployeeData.Employee.PhoneNumber> getPhoneNumberList() {
        if (phoneNumberBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phoneNumber_);
        } else {
          return phoneNumberBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public int getPhoneNumberCount() {
        if (phoneNumberBuilder_ == null) {
          return phoneNumber_.size();
        } else {
          return phoneNumberBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public proto.EmployeeData.Employee.PhoneNumber getPhoneNumber(int index) {
        if (phoneNumberBuilder_ == null) {
          return phoneNumber_.get(index);
        } else {
          return phoneNumberBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder setPhoneNumber(
          int index, proto.EmployeeData.Employee.PhoneNumber value) {
        if (phoneNumberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumberIsMutable();
          phoneNumber_.set(index, value);
          onChanged();
        } else {
          phoneNumberBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder setPhoneNumber(
          int index, proto.EmployeeData.Employee.PhoneNumber.Builder builderForValue) {
        if (phoneNumberBuilder_ == null) {
          ensurePhoneNumberIsMutable();
          phoneNumber_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumberBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder addPhoneNumber(proto.EmployeeData.Employee.PhoneNumber value) {
        if (phoneNumberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumberIsMutable();
          phoneNumber_.add(value);
          onChanged();
        } else {
          phoneNumberBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder addPhoneNumber(
          int index, proto.EmployeeData.Employee.PhoneNumber value) {
        if (phoneNumberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumberIsMutable();
          phoneNumber_.add(index, value);
          onChanged();
        } else {
          phoneNumberBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder addPhoneNumber(
          proto.EmployeeData.Employee.PhoneNumber.Builder builderForValue) {
        if (phoneNumberBuilder_ == null) {
          ensurePhoneNumberIsMutable();
          phoneNumber_.add(builderForValue.build());
          onChanged();
        } else {
          phoneNumberBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder addPhoneNumber(
          int index, proto.EmployeeData.Employee.PhoneNumber.Builder builderForValue) {
        if (phoneNumberBuilder_ == null) {
          ensurePhoneNumberIsMutable();
          phoneNumber_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumberBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder addAllPhoneNumber(
          java.lang.Iterable<? extends proto.EmployeeData.Employee.PhoneNumber> values) {
        if (phoneNumberBuilder_ == null) {
          ensurePhoneNumberIsMutable();
          super.addAll(values, phoneNumber_);
          onChanged();
        } else {
          phoneNumberBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder clearPhoneNumber() {
        if (phoneNumberBuilder_ == null) {
          phoneNumber_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          phoneNumberBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public Builder removePhoneNumber(int index) {
        if (phoneNumberBuilder_ == null) {
          ensurePhoneNumberIsMutable();
          phoneNumber_.remove(index);
          onChanged();
        } else {
          phoneNumberBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public proto.EmployeeData.Employee.PhoneNumber.Builder getPhoneNumberBuilder(
          int index) {
        return getPhoneNumberFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public proto.EmployeeData.Employee.PhoneNumberOrBuilder getPhoneNumberOrBuilder(
          int index) {
        if (phoneNumberBuilder_ == null) {
          return phoneNumber_.get(index);  } else {
          return phoneNumberBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public java.util.List<? extends proto.EmployeeData.Employee.PhoneNumberOrBuilder> 
           getPhoneNumberOrBuilderList() {
        if (phoneNumberBuilder_ != null) {
          return phoneNumberBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phoneNumber_);
        }
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public proto.EmployeeData.Employee.PhoneNumber.Builder addPhoneNumberBuilder() {
        return getPhoneNumberFieldBuilder().addBuilder(
            proto.EmployeeData.Employee.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public proto.EmployeeData.Employee.PhoneNumber.Builder addPhoneNumberBuilder(
          int index) {
        return getPhoneNumberFieldBuilder().addBuilder(
            index, proto.EmployeeData.Employee.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee.PhoneNumber phoneNumber = 3;</code>
       */
      public java.util.List<proto.EmployeeData.Employee.PhoneNumber.Builder> 
           getPhoneNumberBuilderList() {
        return getPhoneNumberFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.EmployeeData.Employee.PhoneNumber, proto.EmployeeData.Employee.PhoneNumber.Builder, proto.EmployeeData.Employee.PhoneNumberOrBuilder> 
          getPhoneNumberFieldBuilder() {
        if (phoneNumberBuilder_ == null) {
          phoneNumberBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.EmployeeData.Employee.PhoneNumber, proto.EmployeeData.Employee.PhoneNumber.Builder, proto.EmployeeData.Employee.PhoneNumberOrBuilder>(
                  phoneNumber_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          phoneNumber_ = null;
        }
        return phoneNumberBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Employee)
    }

    static {
      defaultInstance = new Employee(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Employee)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Employee_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022EmployeeData.proto\"\307\001\n\010Employee\022\r\n\005emp" +
      "Id\030\001 \001(\003\022\017\n\007empName\030\002 \001(\t\022*\n\013phoneNumber" +
      "\030\003 \003(\0132\025.Employee.PhoneNumber\032@\n\013PhoneNu" +
      "mber\022!\n\004type\030\001 \001(\0162\023.Employee.PHONETYPE\022" +
      "\016\n\006number\030\002 \001(\t\"-\n\tPHONETYPE\022\n\n\006MOBILE\020\000" +
      "\022\010\n\004HOME\020\001\022\n\n\006OFFICE\020\002B\025\n\005protoB\014Employe" +
      "eData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Employee_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Employee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Employee_descriptor,
              new java.lang.String[] { "EmpId", "EmpName", "PhoneNumber", });
          internal_static_Employee_PhoneNumber_descriptor =
            internal_static_Employee_descriptor.getNestedTypes().get(0);
          internal_static_Employee_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Employee_PhoneNumber_descriptor,
              new java.lang.String[] { "Type", "Number", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
