
def generate_actions(source, target, env, for_signature):
	# Code to build "target" from "source"
	print "--In generate_actions"
	return "cat < %s > %s" % (source[0], target[0])



env = Environment()

bld = Builder(	generator=generate_actions,
				suffix = '.out',
				src_suffix = '.dummy'
				)

env.Append(BUILDERS={'DummyBuilder':bld}) #Initialize the environment

env.DummyBuilder(target="main", source=["src/main"])
