env = Environment(variant_dir='build', duplicate=0) #Initialize the environment

lib = Split('util boost_system boost_thread')

Export('env lib') # Export function automatically splits the string into a list 

for subdir in ['src']:
	executable = SConscript('%s/SConscript' % subdir, 'env') 
	# SCons Duplicates Source Files in a Variant Directory Tree
	print "Executable create (%s) " % executable

