env = Environment() #Initialize the environment

lib = Split('util boost_system boost_thread')

Export('env lib') # Export function automatically splits the string into a list 

for subdir in ['src']:
	executable = SConscript('%s/SConscript' % subdir, 'env')
	print "Executable create (%s) " % executable

